/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
* */
package io.github.tailhq.dynaml.probability

import breeze.numerics.log
import breeze.stats.distributions.ContinuousDistr
import io.github.tailhq.dynaml.analysis.PushforwardMap
import io.github.tailhq.dynaml.pipes.DataPipe
import io.github.tailhq.dynaml.pipes.Encoder

/**
  *
  * A measurable function is any mapping/function applied
  * to samples generated by some base random variable instance.
  *
  * @tparam Domain1 Type over which the base random variable is defined.
  * @tparam Domain2 Type over which output of function takes its values.
  * @tparam R The type of the base Random Variable, must inherit from [[RandomVariable]]
  * @author tailhq date 24/09/2016.
  *
  * */
trait MeasurableFunction[Domain1, Domain2, +R <: RandomVariable[Domain1]]
  extends RandomVariable[Domain2] {

  val baseRV: R

  val func: DataPipe[Domain1, Domain2]

  def _baseRandomVar: R = baseRV

}

object MeasurableFunction {

  def apply[Domain1, Domain2, R  <: RandomVariable[Domain1]](f: Domain1 => Domain2)(base: R)
  : MeasurableFunction[Domain1, Domain2, R] = new MeasurableFunction[Domain1, Domain2, R] {
    override val baseRV: R                       = base
    override val func                            = DataPipe(f)
    override val sample: DataPipe[Unit, Domain2] = baseRV.sample > func
  }

  def apply[Domain1, Domain2, R <: RandomVariable[Domain1]](base: R)(f: Domain1 => Domain2)
  : MeasurableFunction[Domain1, Domain2, R] = new MeasurableFunction[Domain1, Domain2, R] {
    override val baseRV: R                       = base
    override val func                            = DataPipe(f)
    override val sample: DataPipe[Unit, Domain2] = baseRV.sample > func
  }

  def apply[Domain1, Domain2, R <: RandomVariable[Domain1]](base: R, f: DataPipe[Domain1, Domain2])
  : MeasurableFunction[Domain1, Domain2, R] = new MeasurableFunction[Domain1, Domain2, R] {
    override val baseRV: R                        = base
    override val func: DataPipe[Domain1, Domain2] = f
    override val sample: DataPipe[Unit, Domain2]  = baseRV.sample > func
  }

}

trait ContinuousMeasurableFunc[Domain1, Domain2, +R <: ContinuousRandomVariable[Domain1]]
  extends ContinuousRandomVariable[Domain2] with MeasurableFunction[Domain1, Domain2, R]

object ContinuousMeasurableFunc {
  def apply[
  Domain1,
  Domain2,
  R <: ContinuousRandomVariable[Domain1]](
    f: Domain1 => Domain2)(
    base: R): ContinuousMeasurableFunc[Domain1, Domain2, R] =
    new ContinuousMeasurableFunc[Domain1, Domain2, R] {
      override val baseRV: R                       = base
      override val func                            = DataPipe(f)
      override val sample: DataPipe[Unit, Domain2] = baseRV.sample > func
    }
}

/**
  * A measurable function of a continuous random variable
  * with a defined probability density function.
  *
  * @tparam Domain1 The domain of the base random variable
  * @tparam Domain2 The output set of the function
  * @tparam Jacobian The type representing the Jacobian of inverse of the map [[func]]
  * @param baseRV The base random variable
  * @param func A function with a defined inverse and Jacobian of inverse
  *          as an [[PushforwardMap]] instance.
  *
  * */
class MeasurableDistrRV[Domain1, Domain2, Jacobian, Distr1 <: ContinuousDistr[Domain1]](
  override val baseRV: ContinuousRVWithDistr[Domain1, Distr1])(
  override val func: PushforwardMap[Domain1, Domain2, Jacobian]) extends
  ContinuousMeasurableFunc[
    Domain1, Domain2,
    ContinuousRVWithDistr[Domain1, Distr1]] with
  ContinuousRVWithDistr[Domain2, ContinuousDistr[Domain2]] {

  override val underlyingDist: ContinuousDistr[Domain2] = new ContinuousDistr[Domain2] {

    override def unnormalizedLogPdf(x: Domain2): Double =
      baseRV.underlyingDist.unnormalizedLogPdf(func.i(x)) + log(func._det(func.i.J(x)))

    override def logNormalizer: Double = baseRV.underlyingDist.logNormalizer

    override def draw(): Domain2 = func.run(baseRV.underlyingDist.draw())
  }

}

/**
  * A random variable which consists of a base random variable in [[Domain1]]
  * and an invertible homeomorphism from [[Domain1]] to [[Domain2]].
  *
  * @tparam Domain1 Domain of the base random variable
  * @tparam Domain2 Domain of the morphed random variable.
  * @param base A distribution [[Distr]] over [[Domain1]] which extends breeze [[ContinuousDistr]]
  * @param encoder The morphing function from [[Domain1]] to [[Domain2]]
  * @author tailhq date 16/05/2017.
  * */
class EncodedContDistrRV[
Domain1, Domain2,
Distr <: ContinuousDistr[Domain1]](
  base: Distr, encoder: Encoder[Domain1, Domain2]) extends
  ContinuousRVWithDistr[Domain2, ContinuousDistr[Domain2]] {

  override val underlyingDist: ContinuousDistr[Domain2] = new ContinuousDistr[Domain2] {
    override def unnormalizedLogPdf(x: Domain2): Double = base.unnormalizedLogPdf(encoder.i(x))

    override def logNormalizer: Double = base.logNormalizer

    override def draw(): Domain2 = encoder(base.draw())
  }
}

object EncodedContDistrRV {

  def apply[Domain1, Domain2, Distr <: ContinuousDistr[Domain1]](
    base: Distr, encoder: Encoder[Domain1, Domain2]): EncodedContDistrRV[Domain1, Domain2, Distr] =
    new EncodedContDistrRV(base, encoder)
}